services:

  app:
    build: .
    container_name: student-app
    ports:
      - "8080:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    container_name: student-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
