name: Student Management CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: rootpassword
          POSTGRES_DB: student_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PHP syntax
        run: |
          php -l app/index.php
          php -l app/db.php
          php -l app/test_db.php

      - name: Test PostgreSQL connection
        run: |
          sudo apt-get update
          sudo apt-get install -y php-pgsql
          php -r '$pdo = new PDO("pgsql:host=127.0.0.1;port=5432;dbname=student_db", "postgres", "rootpassword"); echo "Database connection successful!\n";'

